# NumPy DataTypes

In [1]:
import numpy as np

### Ndarrays

In [2]:
array_a = np.array([1,2,3])

In [6]:
print(array_a)

[1 2 3]


In [5]:
type(array_a)

numpy.ndarray

In [7]:
array_a.shape

## "shape" is an attribute of the ndarray, rather than a method, so it's not callable (doesn't need "()" at the end)

(3,)

In [8]:
array_b = np.array([[7,8,9],[10,11,12]])

In [9]:
type(array_b)

numpy.ndarray

In [10]:
print(array_b)

[[ 7  8  9]
 [10 11 12]]


In [13]:
array_b.shape
#array_b.shape[0]
#array_b.shape[1]

## We can use indexing to get a specific part of the output tuple. 

3

In [14]:
array_c = np.array(13)

In [15]:
type(array_c)

## array_c is a 0-D array

numpy.ndarray

In [16]:
print(array_c)

13


In [17]:
array_c.shape

()

In [18]:
array_d = np.array([15])

## We can add square brackets to assign the right number of dimensions to the array we're creating.

In [19]:
type(array_d)

numpy.ndarray

In [20]:
print(array_d)

[15]


In [21]:
array_d.shape

## Similar to array_a from the start of the lecture "(3,)". It's because array_d is a vector of size 1, rather than a scalar.

(1,)

In [22]:
array_e = np.array([[15]])
array_e

array([[15]])

### List vs Array

In [25]:
#list_a = [[1,2,3,4,5,6]]
list_a = [[1,2,3],[4,5,6]]

## Syntax for creating lists is similar to syntax for creating arrays.

In [26]:
len(list_a)

## The length is 2 because we're only counting the sublists of list_a. 

2

In [27]:
array_a = np.array(list_a)

In [28]:
type(list_a)

list

In [29]:
type(array_a)

numpy.ndarray

In [30]:
print(list_a)

[[1, 2, 3], [4, 5, 6]]


In [31]:
print(array_a)

[[1 2 3]
 [4 5 6]]


In [32]:
array_a.shape

(2, 3)

In [36]:
# list_a.shape results in an error because lists don't have a shape.
#len(list_a)

len(list_a[1])

## We can use indexing to refer to a specific sublists out of a list. 

3

In [37]:
list_a

[[1, 2, 3], [4, 5, 6]]

In [38]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
list_b = list_a[0] + list_a[1]
array_b = array_a[0] + array_a[1]

In [40]:
print(list_b)

## The primary purpose of lists is to store data, so list_b concatenates the rows of list_a.

[1, 2, 3, 4, 5, 6]


In [41]:
print(array_b)

## The primary purpose of arrays is computational, so array_b adds the values elementwise.

[5 7 9]


In [44]:
import math
# array_e = math.sqrt(list_a)       # We can't provide an entire list as the input.
# array_e = math.sqrt(list_a[1,0])  # Even individual elements of a list result in an error. 
array_e = math.sqrt(array_a[1,0])
print(array_e)

## The "e" in "array_e" stands for "example".

2.0


In [45]:
np.sqrt(array_a)

## The square root function computes the square root for every element of the array. 

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### String vs Object vs Numbers

In [ ]:
lending_co_lt = np.genfromtxt("lending-co-LT.csv", 
                              delimiter = ',',
                              dtype = np.int32
                              #dtype = np.float16
                              #dtype = np.str
                              #dtype = np.object
                              #dtype = (np.int32, np.str, np.str, np.str, np.str, np.str, np.int32)
                             )
print(lending_co_lt)

# The same dataset is imported differently based on the datatype we define. 

In [ ]:
lending_co_lt[0,0] + lending_co_lt[0,1]